name: smart_home_ui
description: Smart Home UI
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flex_color_scheme: ^7.3.1
  flex_seed_scheme: ^1.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^3.3.5
  go_router: ^12.1.0
  google_fonts: ^6.1.0
  heroicons: ^0.9.0
  intl: ^0.18.0
  redacted: ^1.0.11

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
  - family: GoogleSans
    fonts:
      - asset: assets/fonts/google-sans.ttf
        weight: 500
      - asset: assets/fonts/google-sans-bold.ttf
        weight: 700
      - asset: assets/fonts/google-sans-bolder.ttf
        weight: 900

assets:
  - assets/
  - assets/fonts/

